### PR TITLE
Adding a callback URL to make possible automate fill of key

### PR DESCRIPTION
**Pull request by raelgc**

### CODE REVIEW

**Comment by boonebgorges** [comment]
Hey @raelgc - Thanks for the PR. Just so I understand the implications here: 

* A user signs up for CloudSponge using the link in the admin panel. This link includes a `callback` param, which you store on your end through the checkout process.
* After checkout, you send the user to `{$callback}?cloudsponge_key={$key}`, and the value of `$_GET['cloudsponge_key']` is filled in on the WordPress Dashboard

Is that right? Since the user will still have to save the changes, maybe there should be a "don't forget to save" reminder displayed when `cloudsponge_key` has been provided.

**Comment by raelgc** [comment]
Hi @boonebgorges, how are you, good sir?

Yes, exactly, you got both!

To explain the overall idea: I've reworked all the onboarding process for InviteAnyone users to make it much more simpler.

It'll be just a 3 steps process: signup, purcharsed, click in a button to get back to InviteAnyone. No more confirmation emails, no more complicated screens.

In order to achieve this, like you already got it, in the InviteAnyone side, I'm getting the callback url and automatically filling the admin panel.

About the save button: good idea! I'll include a message to the user!

**Comment by raelgc** [comment]
@boonebgorges I just included the warning message.

**Comment by boonebgorges** [comment]
Thanks!

**Comment by raelgc** [comment]
Welcome, and thank you @boonebgorges for all guidance and help!

One dummie question: is the plugin automatically updated on WP plugins directory after merge or still requires you to publish somewhere?

**Comment by boonebgorges** [comment]
Nope, it doesn't deploy automatically to wordpress.org - I will do it 
later this week, after I make a couple other mods.

**Pull request merged**
