### PR TITLE
 Use BP Theme Compatibility

### PR DESCRIPTION
**Pull request by dcavins**
Use BP's template stack to choose which template to use rather than a custom function. Also creates template files for the two member screens. Tested using BP1.5.7 & 2.1; uses @r-a-y's backpat method.

### CODE REVIEW

**Comment by misfist** [comment]
I'm trying to use a custom template for this plugin in order to more closely replicate BP markup. However, adding `invite-anyone.php` within my theme in `buddypress/groups/single` doesn't seem to work. 

It seems like this function is using the `bp_locate_template` to look into `groups/single`. Any idea why this isn't working?

```php
function invite_anyone_create_screen_content( $event ) {
	if ( !$template = function_exists( 'bp_locate_template' ) ? bp_locate_template( 'groups/single/invite-anyone.php', true ) : locate_template( 'groups/single/invite-anyone.php', true ) ) {
		include_once( 'templates/invite-anyone.php' );
	}
}
```

**Comment by dcavins** [comment]
Hmm. I do exactly what you're asking about using a customized version of the template at `buddypress/groups/single/invite-anyone.php`, and it seems to be working with the most recent version of Invite Anyone. 

Can you double-check that Invite Anyone is running? The invites screen should have the url `<group-name>/invite-anyone/` and the body tag is given the class `invite-anyone`. (Normally, the invites url without IA activated is  `<group-name>/send-invites/`.)

**Comment by boonebgorges** [comment]
A template at `/wp-content/{mytheme}/buddypress/groups/single/invite-anyone.php` is working for me too, as it is for @dcavins. 

In addition to checking whether IA is running, you may want to see whether your theme or some other plugin is doing something funny to the BP template stack. Are you able to override other BP templates by putting them in the corresponding place in `/wp-content/themes/{mytheme}/buddypress/`?

**Comment by boonebgorges** [comment]
Ha, I was going to ask that very thing :) Glad it's working.

**Comment by dcavins** [comment]
Maybe we can safely remove the really-old-BP stuff? 1.2 landed February 16, 2010. Another watershed is 1.7, right? (April 8, 2013)

I've wondered about this before. :)

**Comment by boonebgorges** [comment]
Yeah, it can probably be removed. I recently made a change to the plugin 
that makes it incompatible with anything below 1.8, I think. 
(BP_Group_Members_Query, IIRC). This is a subject for another PR ;)

@dcavins Is the current PR necessary anymore?

**Pull request closed without merging**
