### PR TITLE
feature: Polish language added to the plugin

### PR DESCRIPTION
**Pull request by maksbrzezinski**

### CODE REVIEW

**Comment by boonebgorges** [comment]
Thanks!

**Comment by maksbrzezinski** [comment]
No problem 👍🏻
If you don’t mind adding me to the translation credit, will appreciate it. 

Best, 
--------

Maks Brzeziński
Developer @ MaksDev & Cyberwtyczka
***@***.***
507 929 900

**Comment by boonebgorges** [comment]
Not a problem https://github.com/boonebgorges/invite-anyone/commit/29866b5c0617c8ec5f81298140bfafeb584b1e52 Thanks again!

**Comment by maksbrzezinski** [comment]
No problem and thank you for the credit 🙂On 16 Sep 2024, at 16:44, Boone Gorges ***@***.***> wrote:﻿
Not a problem 29866b5 Thanks again!

**Pull request merged**
